[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
fs_permissions = [{ access = "read-write", path = "./"}]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config